server.port=8443

server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:new.p12
server.ssl.key-store-password=PandaFXThe3
#server.ssl.key-alias=tomcat

#db
spring.datasource.url=jdbc:postgresql://localhost/kick-site
spring.datasource.username=postgres
spring.datasource.password=PandaFXThe3
spring.jpa.generate-ddl=true

spring.mvc.view.prefix=/templates/
spring.mvc.view.suffix=.html


logging.level.web = debug

logging.level.org.springframework.web=DEBUG
spring.mvc.log-request-details=true

